/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (IMap.as).
 */

package org.granite.collections {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class IMapBase implements IExternalizable {

        private var _maxSize:int;
        private var _timestamps:IMap;

        public function readExternal(input:IDataInput):void {
            _maxSize = input.readObject() as int;
            _timestamps = input.readObject() as IMap;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_maxSize);
            output.writeObject(_timestamps);
        }
    }
}