/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (InputStreamLogger.as).
 */

package com.eim.util.logging {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import java.io.InputStream;
    import org.apache.log4j.Level;
    import org.apache.log4j.Logger;

    [Bindable]
    public class InputStreamLoggerBase implements IExternalizable {

        private var _inputStream:InputStream;
        private var _level:Level;
        private var _logger:Logger;

        public function readExternal(input:IDataInput):void {
            _inputStream = input.readObject() as InputStream;
            _level = input.readObject() as Level;
            _logger = input.readObject() as Logger;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_inputStream);
            output.writeObject(_level);
            output.writeObject(_logger);
        }
    }
}