/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.eim.util.exceptions.db {

    [Bindable]
    [RemoteClass(alias="com.eim.util.exceptions.db.InsertException")]
    public class InsertException extends InsertExceptionBase {
    }
}