/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (OracleLob.as).
 */

package com.eim.util.db.lobmanagement.oracle {

    import com.eim.util.db.lobmanagement.LobUtil;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class OracleLobBase implements IExternalizable, LobUtil {


        public function get emptyBlob():Blob {
            return null;
        }

        public function get emptyClob():Clob {
            return null;
        }

        public function readExternal(input:IDataInput):void {
        }

        public function writeExternal(output:IDataOutput):void {
        }
    }
}