/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (GenericKey.as).
 */

package com.eim.util.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class GenericKeyBase implements IExternalizable {

        private var _functionalKey:Boolean;
        private var _name:String;
        private var _value:Object;

        [Bindable(event="unused")]
        public function get functionalKey():Boolean {
            return _functionalKey;
        }

        [Bindable(event="unused")]
        public function get name():String {
            return _name;
        }

        [Bindable(event="unused")]
        public function get value():Object {
            return _value;
        }

        public function readExternal(input:IDataInput):void {
            _functionalKey = input.readObject() as Boolean;
            _name = input.readObject() as String;
            _value = input.readObject() as Object;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_functionalKey);
            output.writeObject(_name);
            output.writeObject(_value);
        }
    }
}