/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.eim.util.model {

    import mx.collections.ListCollectionView;

    public interface IRankingRow {

        function get AUMTotal():Number;

        function get EIMCapacityStatus():String;

        function get EIMInvestments():Number;

        function get EIMRemainingCapacity():Number;

        function get ID():Number;

        function get YTD():ListCollectionView;

        function get YTDTotalReturn():Number;

        function get annualCompoundReturn():Number;

        function get annualizedStandardDeviation():Number;

        function get classificationGroup():String;

        function get classificationGroupID():Number;

        function get currencySymbol():String;

        function get currentDrawdown():Number;

        function get currentReturnDate():Date;

        function get currentReturnValue():Number;

        function get entityType():String;

        function get expectedWorstMonthlyLoss():Number;

        function get exposureGross():Number;

        function get exposureLong():Number;

        function get exposureNet():Number;

        function get exposureShort():Number;

        function get formattedNewMethodology():String;

        function get formattedNewStrategy():String;

        function get formattedNewStyle():String;

        function get formattedRegions():String;

        function get formattedStrategies():String;

        function get fundCapacityStatus():String;

        function get inceptionDate():Date;

        function get kurtosis():Number;

        function get largestDrawdown():Number;

        function get last12MonthsTotalReturn():Number;

        function get last18MonthsAnnualizedReturn():Number;

        function get last18MonthsLargestDrawdown():Number;

        function get last36MonthsAnnualizedReturn():Number;

        function get last3MonthsTotalReturn():Number;

        function get last60MonthsAnnualizedReturn():Number;

        function get last6MonthsTotalReturn():Number;

        function get lastMonthTotalReturnDate():Date;

        function get lastMonthTotalReturnValue():Number;

        function get leverage():Number;

        function get managerSelectionStatus():String;

        function get maximumTimeToRecovery():int;

        function get name():String;

        function get newMainGICSIndustrySectorID():Number;

        function get newMainRegionsGroupID():Number;

        function get numberOfMonths():int;

        function get portfolioCode():String;

        function get portfolioCompanySource():String;

        function get queryDate():Date;

        function get securityType():String;

        function get sharpeRatio():Number;

        function get shortName():String;

        function get skewness():Number;

        function get topLevelCurrencySymbol():String;

        function get topLevelID():Number;

        function get topLevelName():String;

        function get topLevelShortName():String;

        function get totalReturn():Number;

        function get trackRecordStartDate():Date;
    }
}