/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.eim.util.model {

    public interface ISimpleValueToken {

        function set date(value:Date):void;
        function get date():Date;

        function set status(value:String):void;
        function get status():String;

        function set value(value:Number):void;
        function get value():Number;
    }
}