/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (ObjectKey.as).
 */

package com.eim.util.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.granite.collections.IMap;

    [Bindable]
    public class ObjectKeyBase implements IExternalizable {

        private var _functionalKeys:IMap;
        private var _technicalKey:GenericKey;

        [Bindable(event="unused")]
        public function get functionalKeys():IMap {
            return _functionalKeys;
        }

        [Bindable(event="unused")]
        public function get technicalKey():GenericKey {
            return _technicalKey;
        }

        public function readExternal(input:IDataInput):void {
            _functionalKeys = input.readObject() as IMap;
            _technicalKey = input.readObject() as GenericKey;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_functionalKeys);
            output.writeObject(_technicalKey);
        }
    }
}