/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (TimeSlice.as).
 */

package com.eim.util.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class TimeSliceBase extends IdentifiableObject {

        public var _current:Boolean;
        public var _endDate:Date;
        public var _startDate:Date;

        public function set current(value:Boolean):void {
            _current = value;
        }
        public function get current():Boolean {
            return _current;
        }

        public function set endDate(value:Date):void {
            _endDate = value;
        }
        public function get endDate():Date {
            return _endDate;
        }

        public function set startDate(value:Date):void {
            _startDate = value;
        }
        public function get startDate():Date {
            return _startDate;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _current = input.readObject() as Boolean;
            _endDate = input.readObject() as Date;
            _startDate = input.readObject() as Date;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_current);
            output.writeObject(_endDate);
            output.writeObject(_startDate);
        }
    }
}