/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.eim.util.model {

    [Bindable]
    [RemoteClass(alias="com.eim.util.model.TimeSlice")]
    public class TimeSlice extends TimeSliceBase {
    }
}