/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (PimMailer.as).
 */

package com.eim.util.pim {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class PimMailerBase implements IExternalizable {

        protected var _from:String;
        protected var _host:String;
        protected var _to:String;

        public function readExternal(input:IDataInput):void {
            _from = input.readObject() as String;
            _host = input.readObject() as String;
            _to = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_from);
            output.writeObject(_host);
            output.writeObject(_to);
        }
    }
}