/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (VEvent.as).
 */

package com.eim.util.pim {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class VEventBase implements IExternalizable {

        protected var _categories:ListCollectionView;
        protected var _description:String;
        protected var _endDate:Date;
        protected var _location:String;
        protected var _publicFlag:Boolean;
        protected var _startDate:Date;
        protected var _status:String;
        protected var _summary:String;

        public function set categories(value:ListCollectionView):void {
            _categories = value;
        }
        public function get categories():ListCollectionView {
            return _categories;
        }

        public function set description(value:String):void {
            _description = value;
        }
        public function get description():String {
            return _description;
        }

        public function set endDate(value:Date):void {
            _endDate = value;
        }
        public function get endDate():Date {
            return _endDate;
        }

        public function set location(value:String):void {
            _location = value;
        }
        public function get location():String {
            return _location;
        }

        public function set publicFlag(value:Boolean):void {
            _publicFlag = value;
        }
        public function get publicFlag():Boolean {
            return _publicFlag;
        }

        public function set startDate(value:Date):void {
            _startDate = value;
        }
        public function get startDate():Date {
            return _startDate;
        }

        public function set status(value:String):void {
            _status = value;
        }
        public function get status():String {
            return _status;
        }

        public function set summary(value:String):void {
            _summary = value;
        }
        public function get summary():String {
            return _summary;
        }

        public function readExternal(input:IDataInput):void {
            _categories = input.readObject() as ListCollectionView;
            _description = input.readObject() as String;
            _endDate = input.readObject() as Date;
            _location = input.readObject() as String;
            _publicFlag = input.readObject() as Boolean;
            _startDate = input.readObject() as Date;
            _status = input.readObject() as String;
            _summary = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_categories);
            output.writeObject(_description);
            output.writeObject(_endDate);
            output.writeObject(_location);
            output.writeObject(_publicFlag);
            output.writeObject(_startDate);
            output.writeObject(_status);
            output.writeObject(_summary);
        }
    }
}