/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.eim.util.ftp {

    [Bindable]
    [RemoteClass(alias="com.eim.util.ftp.FTPUtil")]
    public class FTPUtil extends FTPUtilBase {
    }
}