/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.eim.util.ejb {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.eim.util.ejb.SessionEJBEvent")]
    public class SessionEJBEvent extends Enum {

        public static const ACTIVATE:SessionEJBEvent = new SessionEJBEvent("ACTIVATE", _);
        public static const PASSIVATE:SessionEJBEvent = new SessionEJBEvent("PASSIVATE", _);
        public static const CREATE:SessionEJBEvent = new SessionEJBEvent("CREATE", _);
        public static const REMOVE:SessionEJBEvent = new SessionEJBEvent("REMOVE", _);

        function SessionEJBEvent(value:String = null, restrictor:* = null) {
            super((value || ACTIVATE.name), restrictor);
        }

        protected override function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [ACTIVATE, PASSIVATE, CREATE, REMOVE];
        }

        public static function valueOf(name:String):SessionEJBEvent {
            return SessionEJBEvent(ACTIVATE.constantOf(name));
        }
    }
}