/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (StatisticsNotEnoughDataException.as).
 */

package com.eim.util.exceptions.statistic {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class StatisticsNotEnoughDataExceptionBase extends StatisticsException {

        private var _afterDate:Date;
        private var _beforeDate:Date;

        [Bindable(event="unused")]
        public function get afterDate():Date {
            return _afterDate;
        }

        [Bindable(event="unused")]
        public function get beforeDate():Date {
            return _beforeDate;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _afterDate = input.readObject() as Date;
            _beforeDate = input.readObject() as Date;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_afterDate);
            output.writeObject(_beforeDate);
        }
    }
}