/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (IterationStatistics.as).
 */

package com.eim.util {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class IterationStatisticsBase implements IExternalizable {

        private var _elapsedTime:Number;
        private var _inIteration:Boolean;
        private var _iterationNb:int;
        private var _iterationStartTime:Number;
        private var _lastRunDuration:Number;
        private var _maxTime:Number;
        private var _minTime:Number;

        public function readExternal(input:IDataInput):void {
            _elapsedTime = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _inIteration = input.readObject() as Boolean;
            _iterationNb = input.readObject() as int;
            _iterationStartTime = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _lastRunDuration = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _maxTime = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _minTime = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_elapsedTime);
            output.writeObject(_inIteration);
            output.writeObject(_iterationNb);
            output.writeObject(_iterationStartTime);
            output.writeObject(_lastRunDuration);
            output.writeObject(_maxTime);
            output.writeObject(_minTime);
        }
    }
}