/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.eim.util {

    [Bindable]
    [RemoteClass(alias="com.eim.util.TreeNode")]
    public class TreeNode extends TreeNodeBase {

        public override function get nodeContent():Object {
            // TODO: Gas3 default generated getter.
            return null;
        }
    }
}