/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Tree.as).
 */

package com.eim.util {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.granite.collections.IMap;

    [Bindable]
    public class TreeBase implements IExternalizable {

        private var _data:IMap;
        private var _root:TreeNode;

        [Bindable(event="unused")]
        public function get root():TreeNode {
            return _root;
        }

        public function readExternal(input:IDataInput):void {
            _data = input.readObject() as IMap;
            _root = input.readObject() as TreeNode;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_data);
            output.writeObject(_root);
        }
    }
}