/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (TreeNode.as).
 */

package com.eim.util {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class TreeNodeBase implements IExternalizable, NodeWrapper {

        private var _children:ListCollectionView;
        private var _content:Object;
        private var _parent:TreeNode;

        [Bindable(event="unused")]
        public function get children():ListCollectionView {
            return _children;
        }

        public function set parent(value:TreeNode):void {
            _parent = value;
        }
        public function get parent():TreeNode {
            return _parent;
        }

        public function get nodeContent():Object {
            return null;
        }

        public function readExternal(input:IDataInput):void {
            _children = input.readObject() as ListCollectionView;
            _content = input.readObject() as Object;
            _parent = input.readObject() as TreeNode;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_children);
            output.writeObject(_content);
            output.writeObject(_parent);
        }
    }
}