/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (CalendarDescription.as).
 */

package com.eim.util.date {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class CalendarDescriptionBase implements IExternalizable {

        protected var _name:String;
        protected var _offDays:ListCollectionView;
        protected var _weekEndDays:ListCollectionView;

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function set offDays(value:ListCollectionView):void {
            _offDays = value;
        }
        public function get offDays():ListCollectionView {
            return _offDays;
        }

        public function set weekEndDays(value:ListCollectionView):void {
            _weekEndDays = value;
        }
        public function get weekEndDays():ListCollectionView {
            return _weekEndDays;
        }

        public function readExternal(input:IDataInput):void {
            _name = input.readObject() as String;
            _offDays = input.readObject() as ListCollectionView;
            _weekEndDays = input.readObject() as ListCollectionView;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_name);
            output.writeObject(_offDays);
            output.writeObject(_weekEndDays);
        }
    }
}