/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (JSONException.as).
 */

package org.json {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import java.lang.Throwable;

    [Bindable]
    public class JSONExceptionBase implements IExternalizable {

        private var _cause:Throwable;

        [Bindable(event="unused")]
        public function get cause():Throwable {
            return _cause;
        }

        public function readExternal(input:IDataInput):void {
            _cause = input.readObject() as Throwable;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_cause);
        }
    }
}