/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (JSONTokener.as).
 */

package org.json {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import java.io.Reader;

    [Bindable]
    public class JSONTokenerBase implements IExternalizable {

        private var _character:int;
        private var _eof:Boolean;
        private var _index:int;
        private var _line:int;
        private var _previous:String;
        private var _reader:Reader;
        private var _usePrevious:Boolean;

        public function readExternal(input:IDataInput):void {
            _character = input.readObject() as int;
            _eof = input.readObject() as Boolean;
            _index = input.readObject() as int;
            _line = input.readObject() as int;
            _previous = input.readObject() as String;
            _reader = input.readObject() as Reader;
            _usePrevious = input.readObject() as Boolean;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_character);
            output.writeObject(_eof);
            output.writeObject(_index);
            output.writeObject(_line);
            output.writeObject(_previous);
            output.writeObject(_reader);
            output.writeObject(_usePrevious);
        }
    }
}