/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (ConcurrentRemoveException.as).
 */

package com.eim.util.exceptions {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class ConcurrentRemoveExceptionBase extends ConcurrentException {

        protected var _entity:String;

        [Bindable(event="unused")]
        public function get entity():String {
            return _entity;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _entity = input.readObject() as String;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_entity);
        }
    }
}