/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Base64.as).
 */

package com.eim.util.security.encription {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class Base64Base implements IExternalizable {


        public function readExternal(input:IDataInput):void {
        }

        public function writeExternal(output:IDataOutput):void {
        }
    }
}