/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (EntryZipDecompressEvent.as).
 */

package com.eim.util.msci.event {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class EntryZipDecompressEventBase extends ZipEvent {

        protected var _entryName:String;

        public function set entryName(value:String):void {
            _entryName = value;
        }
        public function get entryName():String {
            return _entryName;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _entryName = input.readObject() as String;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_entryName);
        }
    }
}