/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.eim.util.msci {

    [Bindable]
    [RemoteClass(alias="com.eim.util.msci.BlockData")]
    public class BlockData extends BlockDataBase {
    }
}