/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (MSCIFundCounterSaxHandler.as).
 */

package com.eim.util.msci {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class MSCIFundCounterSaxHandlerBase implements IExternalizable {

        protected var _fundNb:int;
        protected var _nodePathStack:ListCollectionView;

        [Bindable(event="unused")]
        public function get fundNb():int {
            return _fundNb;
        }

        public function readExternal(input:IDataInput):void {
            _fundNb = input.readObject() as int;
            _nodePathStack = input.readObject() as ListCollectionView;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_fundNb);
            output.writeObject(_nodePathStack);
        }
    }
}