/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (MSCIImporter.as).
 */

package com.eim.util.msci {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import java.io.File;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class MSCIImporterBase implements IExternalizable {

        protected var _fundNb:int;
        protected var _indexNb:int;
        protected var _listeners:ListCollectionView;
        protected var _msciFiles:Array;
        protected var _unzipDone:Boolean;
        protected var _workingDirectory:String;
        protected var _zipFile:File;

        public function readExternal(input:IDataInput):void {
            _fundNb = input.readObject() as int;
            _indexNb = input.readObject() as int;
            _listeners = input.readObject() as ListCollectionView;
            _msciFiles = input.readObject() as Array;
            _unzipDone = input.readObject() as Boolean;
            _workingDirectory = input.readObject() as String;
            _zipFile = input.readObject() as File;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_fundNb);
            output.writeObject(_indexNb);
            output.writeObject(_listeners);
            output.writeObject(_msciFiles);
            output.writeObject(_unzipDone);
            output.writeObject(_workingDirectory);
            output.writeObject(_zipFile);
        }
    }
}