/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (MSCIImportedData.as).
 */

package com.eim.util.msci {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class MSCIImportedDataBase implements IExternalizable {

        protected var _data:XML;
        protected var _extractionDate:Date;

        [Bindable(event="unused")]
        public function get data():XML {
            return _data;
        }

        [Bindable(event="unused")]
        public function get extractionDate():Date {
            return _extractionDate;
        }

        public function readExternal(input:IDataInput):void {
            _data = input.readObject() as XML;
            _extractionDate = input.readObject() as Date;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_data);
            output.writeObject(_extractionDate);
        }
    }
}