/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (CheckDataFailureException.as).
 */

package com.eim.util.exceptions.validation {

    import com.eim.util.exceptions.EIMException;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.collections.IMap;

    [Bindable]
    public class CheckDataFailureExceptionBase extends EIMException {

        private var _failures:IMap;

        [Bindable(event="unused")]
        public function get failures():IMap {
            return _failures;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _failures = input.readObject() as IMap;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_failures);
        }
    }
}