/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (InvalidDateRangeException.as).
 */

package com.eim.util.exceptions.validation {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class InvalidDateRangeExceptionBase extends InvalidDateException {

        protected var _fundName:String;

        public function set fundName(value:String):void {
            _fundName = value;
        }
        public function get fundName():String {
            return _fundName;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _fundName = input.readObject() as String;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_fundName);
        }
    }
}