/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (InvalidSearchException.as).
 */

package com.eim.util.exceptions.validation {

    import com.eim.util.exceptions.EIMRuntimeException;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class InvalidSearchExceptionBase extends EIMRuntimeException {


        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
        }
    }
}