/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (ValidationParameter.as).
 */

package com.eim.util.exceptions.validation {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class ValidationParameterBase implements IExternalizable {

        private var _alias:String;
        private var _parameter:Object;

        [Bindable(event="unused")]
        public function get alias():String {
            return _alias;
        }

        [Bindable(event="unused")]
        public function get parameter():Object {
            return _parameter;
        }

        public function readExternal(input:IDataInput):void {
            _alias = input.readObject() as String;
            _parameter = input.readObject() as Object;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_alias);
            output.writeObject(_parameter);
        }
    }
}