/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.eim.util.livelink {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.eim.util.livelink.LivelinkDocumentType")]
    public class LivelinkDocumentType extends Enum {

        public static const ARTICLES_OF_ASSOCIATION:LivelinkDocumentType = new LivelinkDocumentType("ARTICLES_OF_ASSOCIATION", _);
        public static const COLLATERAL_MANAGEMENT_AND_RELATED_SERVICES_AGREEMENT:LivelinkDocumentType = new LivelinkDocumentType("COLLATERAL_MANAGEMENT_AND_RELATED_SERVICES_AGREEMENT", _);
        public static const CONSTITUTIVE_DOCUMENT:LivelinkDocumentType = new LivelinkDocumentType("CONSTITUTIVE_DOCUMENT", _);
        public static const CORPORATE_ACTION:LivelinkDocumentType = new LivelinkDocumentType("CORPORATE_ACTION", _);
        public static const CORPORATE_ADMINISTRATOR_AGREEMENT:LivelinkDocumentType = new LivelinkDocumentType("CORPORATE_ADMINISTRATOR_AGREEMENT", _);
        public static const CURRENCY_HEDGE_ADMINISTRATION_AGREEMENT:LivelinkDocumentType = new LivelinkDocumentType("CURRENCY_HEDGE_ADMINISTRATION_AGREEMENT", _);
        public static const CURRENCY_HEDGE_AGREEMENT:LivelinkDocumentType = new LivelinkDocumentType("CURRENCY_HEDGE_AGREEMENT", _);
        public static const CUSTODY_AGREEMENT:LivelinkDocumentType = new LivelinkDocumentType("CUSTODY_AGREEMENT", _);
        public static const DUE_DILIGENCE_GLOBAL:LivelinkDocumentType = new LivelinkDocumentType("DUE_DILIGENCE_GLOBAL", _);
        public static const DUE_DILIGENCE_MANAGER_BACKGROUND_CHECK:LivelinkDocumentType = new LivelinkDocumentType("DUE_DILIGENCE_MANAGER_BACKGROUND_CHECK", _);
        public static const DUE_DILIGENCE_ONSITE_OPERATIONAL_UPDATE:LivelinkDocumentType = new LivelinkDocumentType("DUE_DILIGENCE_ONSITE_OPERATIONAL_UPDATE", _);
        public static const DUE_DILIGENCE_OPERATIONAL:LivelinkDocumentType = new LivelinkDocumentType("DUE_DILIGENCE_OPERATIONAL", _);
        public static const DUE_DILIGENCE_QUALITATIVE:LivelinkDocumentType = new LivelinkDocumentType("DUE_DILIGENCE_QUALITATIVE", _);
        public static const DUE_DILIGENCE_QUANT:LivelinkDocumentType = new LivelinkDocumentType("DUE_DILIGENCE_QUANT", _);
        public static const DUE_DILIGENCE_QUESTIONNAIRE:LivelinkDocumentType = new LivelinkDocumentType("DUE_DILIGENCE_QUESTIONNAIRE", _);
        public static const FINANCIAL_STATEMENT:LivelinkDocumentType = new LivelinkDocumentType("FINANCIAL_STATEMENT", _);
        public static const FORM_ADV:LivelinkDocumentType = new LivelinkDocumentType("FORM_ADV", _);
        public static const FULL_ANALYTICAL_REPORT:LivelinkDocumentType = new LivelinkDocumentType("FULL_ANALYTICAL_REPORT", _);
        public static const FUND_ADMINISTRATOR_AGREEMENT:LivelinkDocumentType = new LivelinkDocumentType("FUND_ADMINISTRATOR_AGREEMENT", _);
        public static const FUND_LIQUIDITY_SHEET:LivelinkDocumentType = new LivelinkDocumentType("FUND_LIQUIDITY_SHEET", _);
        public static const FUND_PROXIES:LivelinkDocumentType = new LivelinkDocumentType("FUND_PROXIES", _);
        public static const HIGHLIGHT_REPORT_RESEARCH:LivelinkDocumentType = new LivelinkDocumentType("HIGHLIGHT_REPORT_RESEARCH", _);
        public static const INVESTMENT_LETTER:LivelinkDocumentType = new LivelinkDocumentType("INVESTMENT_LETTER", _);
        public static const KYC_PROCEDURE:LivelinkDocumentType = new LivelinkDocumentType("KYC_PROCEDURE", _);
        public static const LIQUIDITY_SERVICES_AGREEMENT:LivelinkDocumentType = new LivelinkDocumentType("LIQUIDITY_SERVICES_AGREEMENT", _);
        public static const MANAGER_INFO_AND_CONTRACTS:LivelinkDocumentType = new LivelinkDocumentType("MANAGER_INFO_AND_CONTRACTS", _);
        public static const MARKETING_MATERIAL:LivelinkDocumentType = new LivelinkDocumentType("MARKETING_MATERIAL", _);
        public static const OFFERING_MEMORANDUM:LivelinkDocumentType = new LivelinkDocumentType("OFFERING_MEMORANDUM", _);
        public static const ON_SITE_VISIT:LivelinkDocumentType = new LivelinkDocumentType("ON_SITE_VISIT", _);
        public static const OTHER_HIERARCHY_RELATED_DOCUMENT:LivelinkDocumentType = new LivelinkDocumentType("OTHER_HIERARCHY_RELATED_DOCUMENT", _);
        public static const PRIME_BROKER_MARGIN_ACCOUNT_AGREEMENT:LivelinkDocumentType = new LivelinkDocumentType("PRIME_BROKER_MARGIN_ACCOUNT_AGREEMENT", _);
        public static const PRIME_BROKERAGE_AGREEMENT:LivelinkDocumentType = new LivelinkDocumentType("PRIME_BROKERAGE_AGREEMENT", _);
        public static const QUANTITATIVE:LivelinkDocumentType = new LivelinkDocumentType("QUANTITATIVE", _);
        public static const REDEMPTION_FORM:LivelinkDocumentType = new LivelinkDocumentType("REDEMPTION_FORM", _);
        public static const REQUEST_FOR_PROPOSAL:LivelinkDocumentType = new LivelinkDocumentType("REQUEST_FOR_PROPOSAL", _);
        public static const RISK_ANALYSIS:LivelinkDocumentType = new LivelinkDocumentType("RISK_ANALYSIS", _);
        public static const RISK_MONITOR_AGREEMENT:LivelinkDocumentType = new LivelinkDocumentType("RISK_MONITOR_AGREEMENT", _);
        public static const SHORT_ANALYTICAL_REPORT:LivelinkDocumentType = new LivelinkDocumentType("SHORT_ANALYTICAL_REPORT", _);
        public static const SIMPLIFIED_PROSPECTUS:LivelinkDocumentType = new LivelinkDocumentType("SIMPLIFIED_PROSPECTUS", _);
        public static const SUBSCRIPTION_FORM:LivelinkDocumentType = new LivelinkDocumentType("SUBSCRIPTION_FORM", _);
        public static const SUBSCRIPTION_FORM_FOR_ADDITIONAL_INVESTMENT:LivelinkDocumentType = new LivelinkDocumentType("SUBSCRIPTION_FORM_FOR_ADDITIONAL_INVESTMENT", _);
        public static const SUPPLEMENTAL_ADMINISTRATION_AGREEMENT:LivelinkDocumentType = new LivelinkDocumentType("SUPPLEMENTAL_ADMINISTRATION_AGREEMENT", _);
        public static const TRADING_ADVISER_AGREEMENT:LivelinkDocumentType = new LivelinkDocumentType("TRADING_ADVISER_AGREEMENT", _);
        public static const TRADING_ADVISER_SUPPLEMENT:LivelinkDocumentType = new LivelinkDocumentType("TRADING_ADVISER_SUPPLEMENT", _);
        public static const TRANSFER_FORM:LivelinkDocumentType = new LivelinkDocumentType("TRANSFER_FORM", _);
        public static const UNKNOWN:LivelinkDocumentType = new LivelinkDocumentType("UNKNOWN", _);
        public static const AUDITED_FINANCIALS:LivelinkDocumentType = new LivelinkDocumentType("AUDITED_FINANCIALS", _);
        public static const AUDIT_REPORT_CHECKLIST:LivelinkDocumentType = new LivelinkDocumentType("AUDIT_REPORT_CHECKLIST", _);
        public static const BUY_WATCH_SELL_NOTES:LivelinkDocumentType = new LivelinkDocumentType("BUY_WATCH_SELL_NOTES", _);
        public static const CORRELATION_REPORT:LivelinkDocumentType = new LivelinkDocumentType("CORRELATION_REPORT", _);
        public static const MANAGER_FACT_SHEET:LivelinkDocumentType = new LivelinkDocumentType("MANAGER_FACT_SHEET", _);
        public static const MONTHLY_STAT:LivelinkDocumentType = new LivelinkDocumentType("MONTHLY_STAT", _);
        public static const MANAGER_REPORT:LivelinkDocumentType = new LivelinkDocumentType("MANAGER_REPORT", _);
        public static const MONTHLY_REPORT_CLIENT:LivelinkDocumentType = new LivelinkDocumentType("MONTHLY_REPORT_CLIENT", _);
        public static const MONTHLY_REPORT_RESEARCH:LivelinkDocumentType = new LivelinkDocumentType("MONTHLY_REPORT_RESEARCH", _);
        public static const MONTHLY_REPORT_TEMPLATE:LivelinkDocumentType = new LivelinkDocumentType("MONTHLY_REPORT_TEMPLATE", _);
        public static const QUALITATIVE_SCORING_CARDS:LivelinkDocumentType = new LivelinkDocumentType("QUALITATIVE_SCORING_CARDS", _);
        public static const QUARTERLY_REPORT_CLIENT:LivelinkDocumentType = new LivelinkDocumentType("QUARTERLY_REPORT_CLIENT", _);
        public static const QUARTERLY_REPORT_RESEARCH:LivelinkDocumentType = new LivelinkDocumentType("QUARTERLY_REPORT_RESEARCH", _);
        public static const HIGHLIGHT_REPORT_CLIENT:LivelinkDocumentType = new LivelinkDocumentType("HIGHLIGHT_REPORT_CLIENT", _);
        public static const NONE:LivelinkDocumentType = new LivelinkDocumentType("NONE", _);
        public static const MANAGER_QUARTERLY_REPORT:LivelinkDocumentType = new LivelinkDocumentType("MANAGER_QUARTERLY_REPORT", _);
        public static const LUMX_RISK_REPORT:LivelinkDocumentType = new LivelinkDocumentType("LUMX_RISK_REPORT", _);
        public static const MANAGER_ANNUAL_REPORT:LivelinkDocumentType = new LivelinkDocumentType("MANAGER_ANNUAL_REPORT", _);
        public static const MANAGER_RISK_REPORT:LivelinkDocumentType = new LivelinkDocumentType("MANAGER_RISK_REPORT", _);
        public static const MANAGER_EXPOSURE_REPORT:LivelinkDocumentType = new LivelinkDocumentType("MANAGER_EXPOSURE_REPORT", _);
        public static const MANAGER_COMMENT:LivelinkDocumentType = new LivelinkDocumentType("MANAGER_COMMENT", _);
        public static const MANAGER_PORTFOLIO_DETAILS:LivelinkDocumentType = new LivelinkDocumentType("MANAGER_PORTFOLIO_DETAILS", _);
        public static const BREACH:LivelinkDocumentType = new LivelinkDocumentType("BREACH", _);
        public static const ONE_PAGE:LivelinkDocumentType = new LivelinkDocumentType("ONE_PAGE", _);
        public static const SIDE_LETTER:LivelinkDocumentType = new LivelinkDocumentType("SIDE_LETTER", _);
        public static const INVESTMENT_GUIDELINES_FLAG:LivelinkDocumentType = new LivelinkDocumentType("INVESTMENT_GUIDELINES_FLAG", _);
        public static const QUARTERLY_RISK_ANALYSIS:LivelinkDocumentType = new LivelinkDocumentType("QUARTERLY_RISK_ANALYSIS", _);

        function LivelinkDocumentType(value:String = null, restrictor:* = null) {
            super((value || ARTICLES_OF_ASSOCIATION.name), restrictor);
        }

        protected override function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [ARTICLES_OF_ASSOCIATION, COLLATERAL_MANAGEMENT_AND_RELATED_SERVICES_AGREEMENT, CONSTITUTIVE_DOCUMENT, CORPORATE_ACTION, CORPORATE_ADMINISTRATOR_AGREEMENT, CURRENCY_HEDGE_ADMINISTRATION_AGREEMENT, CURRENCY_HEDGE_AGREEMENT, CUSTODY_AGREEMENT, DUE_DILIGENCE_GLOBAL, DUE_DILIGENCE_MANAGER_BACKGROUND_CHECK, DUE_DILIGENCE_ONSITE_OPERATIONAL_UPDATE, DUE_DILIGENCE_OPERATIONAL, DUE_DILIGENCE_QUALITATIVE, DUE_DILIGENCE_QUANT, DUE_DILIGENCE_QUESTIONNAIRE, FINANCIAL_STATEMENT, FORM_ADV, FULL_ANALYTICAL_REPORT, FUND_ADMINISTRATOR_AGREEMENT, FUND_LIQUIDITY_SHEET, FUND_PROXIES, HIGHLIGHT_REPORT_RESEARCH, INVESTMENT_LETTER, KYC_PROCEDURE, LIQUIDITY_SERVICES_AGREEMENT, MANAGER_INFO_AND_CONTRACTS, MARKETING_MATERIAL, OFFERING_MEMORANDUM, ON_SITE_VISIT, OTHER_HIERARCHY_RELATED_DOCUMENT, PRIME_BROKER_MARGIN_ACCOUNT_AGREEMENT, PRIME_BROKERAGE_AGREEMENT, QUANTITATIVE, REDEMPTION_FORM, REQUEST_FOR_PROPOSAL, RISK_ANALYSIS, RISK_MONITOR_AGREEMENT, SHORT_ANALYTICAL_REPORT, SIMPLIFIED_PROSPECTUS, SUBSCRIPTION_FORM, SUBSCRIPTION_FORM_FOR_ADDITIONAL_INVESTMENT, SUPPLEMENTAL_ADMINISTRATION_AGREEMENT, TRADING_ADVISER_AGREEMENT, TRADING_ADVISER_SUPPLEMENT, TRANSFER_FORM, UNKNOWN, AUDITED_FINANCIALS, AUDIT_REPORT_CHECKLIST, BUY_WATCH_SELL_NOTES, CORRELATION_REPORT, MANAGER_FACT_SHEET, MONTHLY_STAT, MANAGER_REPORT, MONTHLY_REPORT_CLIENT, MONTHLY_REPORT_RESEARCH, MONTHLY_REPORT_TEMPLATE, QUALITATIVE_SCORING_CARDS, QUARTERLY_REPORT_CLIENT, QUARTERLY_REPORT_RESEARCH, HIGHLIGHT_REPORT_CLIENT, NONE, MANAGER_QUARTERLY_REPORT, LUMX_RISK_REPORT, MANAGER_ANNUAL_REPORT, MANAGER_RISK_REPORT, MANAGER_EXPOSURE_REPORT, MANAGER_COMMENT, MANAGER_PORTFOLIO_DETAILS, BREACH, ONE_PAGE, SIDE_LETTER, INVESTMENT_GUIDELINES_FLAG, QUARTERLY_RISK_ANALYSIS];
        }

        public static function valueOf(name:String):LivelinkDocumentType {
            return LivelinkDocumentType(ARTICLES_OF_ASSOCIATION.constantOf(name));
        }
    }
}