/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.eim.util.db.lobmanagement {

    [Bindable]
    [RemoteClass(alias="com.eim.util.db.lobmanagement.LobUtilFactory")]
    public class LobUtilFactory extends LobUtilFactoryBase {
    }
}