/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.eim.util.db.lobmanagement {

    import java.sql.Blob;
    import java.sql.Clob;

    public interface LobUtil {

        function get emptyBlob():Blob;

        function get emptyClob():Clob;
    }
}