/**
 * Generated by Gas3 v2.2.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (ComparisonStorage.as).
 */

package com.eim.util.xml {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class ComparisonStorageBase implements IExternalizable {

        private var _childResults:ListCollectionView;
        private var _result:XmlComparisonResult;

        public function readExternal(input:IDataInput):void {
            _childResults = input.readObject() as ListCollectionView;
            _result = input.readObject() as XmlComparisonResult;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_childResults);
            output.writeObject(_result);
        }
    }
}